[package]
name = "bed"
version = "0.0.1"
authors = ["Srimanta Barua <srimanta.barua1@gmail.com>"]
edition = "2018"


[dependencies]
clap = "2.33"
crossbeam-channel = "0.4.2"
directories = "2.0"
euclid = "0.20.7"
fnv = "1.0.6"
freetype = "0.4.1"
gl = "0.14"
glfw  = "0.37"
guillotiere = "0.4.3"
harfbuzz-sys = "0.3.4"
ropey = "1.1"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
syntect = { version = "4.1.1", default-features = false, features = ["default-fancy"] }
unicode-segmentation = "1.6"

[target.'cfg(unix)'.dependencies]
servo-fontconfig = "0.4"

[target.'cfg(windows)'.dependencies]
com-wrapper = "0.1.0"
directwrite = "0.3.0-alpha4"
winapi = "0.3.8"


[profile.dev]
opt-level = 0
debug = 2


[profile.release]
opt-level = 3
debug = 0
