[package]
name = "bed"
version = "0.0.1"
authors = ["Srimanta Barua <srimanta.barua1@gmail.com>"]
description = "Barua's EDitor"
edition = "2018"

[dependencies]
euclid = "0.20.13"
gl = "0.14.0"
glutin = "0.24.1"
