// (C) 2020 Srimanta Barua <srimanta.barua1@gmail.com>

use crate::types::Tag;

macro_rules! features {
    ($pt:vis $name:ident { $( $feat:ident $stag:expr ),* } ) => {
        #[derive(Debug)]
        $pt enum $name {
            $( $feat ),*
        }

        impl $name {
            pub(crate) const fn tag(&self) -> Tag {
                match self {
                    $( $name::$feat => Tag::from($stag) ),*
                }
            }
        }
    };
}

// User-accessible features
features!(pub Features {
    AccessAllAlternatives                 b"aalt",
    AboveBaseForms                        b"abvf",
    AboveBaseMarkPositioning              b"abvm",
    AboveBaseSubstitutions                b"abvs",
    AlternateFractions                    b"afrc",
    Akhand                                b"akhn",
    BelowBaseForms                        b"blwf",
    BelowBaseMarkPositioning              b"blwm",
    BelowBaseSubstitutions                b"blws",
    ContextualAlternatives                b"calt",
    CaseSensitiveForms                    b"case",
    GlyphCompositionDecomposition         b"ccmp",
    ConjunctFormAfterRo                   b"cfar",
    ContextualHalfWidthSpacing            b"chws",
    ConjunctForms                         b"cjct",
    ContextualLigatures                   b"clig",
    CenteredCJKPunctuation                b"cpct",
    CapitalSpacing                        b"cpsp",
    ContextualSwash                       b"cswh",
    CursivePositioning                    b"curs",
    CharacterVariant01                    b"cv01",
    CharacterVariant02                    b"cv02",
    CharacterVariant03                    b"cv03",
    CharacterVariant04                    b"cv04",
    CharacterVariant05                    b"cv05",
    CharacterVariant06                    b"cv06",
    CharacterVariant07                    b"cv07",
    CharacterVariant08                    b"cv08",
    CharacterVariant09                    b"cv09",
    CharacterVariant10                    b"cv10",
    CharacterVariant11                    b"cv11",
    CharacterVariant12                    b"cv12",
    CharacterVariant13                    b"cv13",
    CharacterVariant14                    b"cv14",
    CharacterVariant15                    b"cv15",
    CharacterVariant16                    b"cv16",
    CharacterVariant17                    b"cv17",
    CharacterVariant18                    b"cv18",
    CharacterVariant19                    b"cv19",
    CharacterVariant20                    b"cv20",
    CharacterVariant21                    b"cv21",
    CharacterVariant22                    b"cv22",
    CharacterVariant23                    b"cv23",
    CharacterVariant24                    b"cv24",
    CharacterVariant25                    b"cv25",
    CharacterVariant26                    b"cv26",
    CharacterVariant27                    b"cv27",
    CharacterVariant28                    b"cv28",
    CharacterVariant29                    b"cv29",
    CharacterVariant30                    b"cv30",
    CharacterVariant31                    b"cv31",
    CharacterVariant32                    b"cv32",
    CharacterVariant33                    b"cv33",
    CharacterVariant34                    b"cv34",
    CharacterVariant35                    b"cv35",
    CharacterVariant36                    b"cv36",
    CharacterVariant37                    b"cv37",
    CharacterVariant38                    b"cv38",
    CharacterVariant39                    b"cv39",
    CharacterVariant40                    b"cv40",
    CharacterVariant41                    b"cv41",
    CharacterVariant42                    b"cv42",
    CharacterVariant43                    b"cv43",
    CharacterVariant44                    b"cv44",
    CharacterVariant45                    b"cv45",
    CharacterVariant46                    b"cv46",
    CharacterVariant47                    b"cv47",
    CharacterVariant48                    b"cv48",
    CharacterVariant49                    b"cv49",
    CharacterVariant50                    b"cv50",
    CharacterVariant51                    b"cv51",
    CharacterVariant52                    b"cv52",
    CharacterVariant53                    b"cv53",
    CharacterVariant54                    b"cv54",
    CharacterVariant55                    b"cv55",
    CharacterVariant56                    b"cv56",
    CharacterVariant57                    b"cv57",
    CharacterVariant58                    b"cv58",
    CharacterVariant59                    b"cv59",
    CharacterVariant60                    b"cv60",
    CharacterVariant61                    b"cv61",
    CharacterVariant62                    b"cv62",
    CharacterVariant63                    b"cv63",
    CharacterVariant64                    b"cv64",
    CharacterVariant65                    b"cv65",
    CharacterVariant66                    b"cv66",
    CharacterVariant67                    b"cv67",
    CharacterVariant68                    b"cv68",
    CharacterVariant69                    b"cv69",
    CharacterVariant70                    b"cv70",
    CharacterVariant71                    b"cv71",
    CharacterVariant72                    b"cv72",
    CharacterVariant73                    b"cv73",
    CharacterVariant74                    b"cv74",
    CharacterVariant75                    b"cv75",
    CharacterVariant76                    b"cv76",
    CharacterVariant77                    b"cv77",
    CharacterVariant78                    b"cv78",
    CharacterVariant79                    b"cv79",
    CharacterVariant80                    b"cv80",
    CharacterVariant81                    b"cv81",
    CharacterVariant82                    b"cv82",
    CharacterVariant83                    b"cv83",
    CharacterVariant84                    b"cv84",
    CharacterVariant85                    b"cv85",
    CharacterVariant86                    b"cv86",
    CharacterVariant87                    b"cv87",
    CharacterVariant88                    b"cv88",
    CharacterVariant89                    b"cv89",
    CharacterVariant90                    b"cv90",
    CharacterVariant91                    b"cv91",
    CharacterVariant92                    b"cv92",
    CharacterVariant93                    b"cv93",
    CharacterVariant94                    b"cv94",
    CharacterVariant95                    b"cv95",
    CharacterVariant96                    b"cv96",
    CharacterVariant97                    b"cv97",
    CharacterVariant98                    b"cv98",
    CharacterVariant99                    b"cv99",
    PetiteCapitalsFromCapitals            b"c2pc",
    SmallCapitalsFromCapitals             b"c2sc",
    Distances                             b"dist",
    DiscretionaryLigatures                b"dlig",
    Denominators                          b"dnom", // Enabled on denominator of fraction
    DotlessForms                          b"dtls",
    ExpertForms                           b"expt",
    FinalGlyphOnLineAlternates            b"falt",
    TerminalForm2                         b"fin2",
    TerminalForm3                         b"fin3",
    TerminalForms                         b"fina",
    FlattenedAscentForms                  b"flac",
    Fractions                             b"frac", // Enabled when fraction is detected
    FullWidths                            b"fwid",
    HalfForms                             b"half",
    HalantForms                           b"haln",
    AlternateHalfWidths                   b"halt",
    HistoricalForms                       b"hist",
    HorizontalKanaAlternates              b"hkna",
    HistoricalLigatures                   b"hlig",
    Hangul                                b"hngl", // DEPRECATED
    HojoKanjiForms                        b"hojo",
    HalfWidths                            b"hwid",
    InitialForms                          b"init",
    IsolatedForms                         b"isol",
    Italics                               b"ital",
    JustificationAlternates               b"jalt",
    JIS78Forms                            b"jp78",
    JIS83Forms                            b"jp83",
    JIS90Forms                            b"jp90",
    JIS2004Forms                          b"jp04",
    Kerning                               b"kern",
    LeftBounds                            b"lfbd",
    StandardLigatures                     b"liga",
    LeadingJamoForms                      b"ljmo",
    LiningFigures                         b"lnum",
    LocalizedForms                        b"locl",
    LeftToRightGlyphAlternates            b"ltra",
    LeftToRightMirroredForms              b"ltrm",
    MarkPositioning                       b"mark",
    MedialForms2                          b"med2",
    MedialForms                           b"medi",
    MathematicalGreek                     b"mgrk",
    MarkToMarkPositioning                 b"mkmk",
    Mset                                  b"mset",
    AlternateAnnotationForms              b"nalt",
    NLCKanjiForms                         b"nlck",
    NuktaForms                            b"nukt",
    Numerators                            b"numr", // Enabled on numerator part of fraction
    OldstyleFigures                       b"onum",
    OpticalBounds                         b"opbd", // DEPRECATED
    Ordinals                              b"ordn",
    Ornaments                             b"ornm",
    ProportionalAlternateWidths           b"palt",
    PetiteCapitals                        b"pcap",
    ProportionalKana                      b"pkna",
    ProportionalFigures                   b"pnum",
    PreBaseForms                          b"pref",
    PreBaseSubstitutions                  b"pres",
    PostBaseForms                         b"pstf",
    PostBaseSubstitutions                 b"psts",
    ProportionalWidths                    b"pwid",
    QuarterWidths                         b"qwid",
    Randomize                             b"rand",
    RequiredContextualAlternates          b"rclt",
    RakarForms                            b"rkrf",
    RequiredLigatures                     b"rlig",
    RephForm                              b"rphf",
    RightBounds                           b"rtbd",
    RightToLeftAlternates                 b"rtla",
    RightToLeftMirroredForms              b"rtlm",
    RubyNotationForms                     b"ruby",
    RequiredVariationAlternates           b"rvrn",
    StylisticAlternates                   b"salt",
    ScientificInferiors                   b"sinf",
    OpticalSize                           b"size",
    SmallCapitals                         b"smcp",
    SimplifiedForms                       b"smpl",
    StylisticSet01                        b"ss01",
    StylisticSet02                        b"ss02",
    StylisticSet03                        b"ss03",
    StylisticSet04                        b"ss04",
    StylisticSet05                        b"ss05",
    StylisticSet06                        b"ss06",
    StylisticSet07                        b"ss07",
    StylisticSet08                        b"ss08",
    StylisticSet09                        b"ss09",
    StylisticSet10                        b"ss10",
    StylisticSet11                        b"ss11",
    StylisticSet12                        b"ss12",
    StylisticSet13                        b"ss13",
    StylisticSet14                        b"ss14",
    StylisticSet15                        b"ss15",
    StylisticSet16                        b"ss16",
    StylisticSet17                        b"ss17",
    StylisticSet18                        b"ss18",
    StylisticSet19                        b"ss19",
    StylisticSet20                        b"ss20",
    MathScriptStyleAlternates             b"ssty",
    StretchingGlyphDecomposition          b"stch",
    Subscript                             b"subs",
    Superscript                           b"sups",
    Swash                                 b"swsh",
    Titling                               b"titl",
    TrailingJamoForms                     b"tjmo",
    TraditionalNameForms                  b"tnam",
    TabularFigures                        b"tnum",
    TraditionalForms                      b"trad",
    ThirdWidths                           b"twid",
    Unicase                               b"unic",
    AlternateVerticalMetrics              b"valt",
    VattuVariants                         b"vatu",
    VerticalContextualHalfWidthSpacing    b"vchw",
    VerticalAlternates                    b"vert",
    AlternateVerticalHalfMetrics          b"vhal",
    VowelJamoForms                        b"vjmo",
    VerticalKanaAlternates                b"vkna",
    VerticalKerning                       b"vkrn",
    ProportionalAlternateVerticalMetrics  b"vpal",
    VerticalAlternatesAndRotation         b"vrt2",
    VerticalAlternatesForRotation         b"vrtr",
    SlashedZero                           b"zero"
} );

pub(crate) static DEFAULT_FEATURES: [Features; 7] = [
    Features::AboveBaseMarkPositioning,
    Features::BelowBaseMarkPositioning,
    Features::GlyphCompositionDecomposition,
    Features::LocalizedForms,
    Features::MarkPositioning,
    Features::MarkToMarkPositioning,
    Features::RequiredLigatures,
];

pub(crate) static HORIZONTAL_FEATURES: [Features; 7] = [
    Features::ContextualAlternatives,
    Features::ContextualLigatures,
    Features::CursivePositioning,
    Features::Distances,
    Features::Kerning,
    Features::StandardLigatures,
    Features::RequiredContextualAlternates,
];

pub(crate) static VERTICAL_FEATURES: [Features; 1] = [Features::VerticalAlternates];
