// (C) 2020 Srimanta Barua <srimanta.barua1@gmail.com>

use crate::types::Tag;

#[derive(Debug)]
pub enum Script {
    Adlam,
    Ahom,
    AnatolianHieroglyphs,
    Arabic,
    Armenian,
    Avestan,
    Balinese,
    Bamum,
    BassaVah,
    Batak,
    Bengali,
    BengaliV2,
    Bhaiksuki,
    Bopomofo,
    Brahmi,
    Braille,
    Buginese,
    Buhid,
    ByzantineMusic,
    CanadianSyllabics,
    Carian,
    CaucasianAlbanian,
    Chakma,
    Cham,
    Cherokee,
    Chorasmian,
    CJKIdeographic,
    Coptic,
    CypriotSyllabary,
    Cyrillic,
    Default,
    Deseret,
    Devanagari,
    DevanagariV2,
    DivesAkuru,
    Dogra,
    Duployan,
    EgyptianHieroglyphs,
    Elbasan,
    Elymaic,
    Ethiopic,
    Georgian,
    Glagolitic,
    Gothic,
    Grantha,
    Greek,
    Gujarati,
    GujaratiV2,
    GunjalaGondi,
    Gurmukhi,
    GurmukhiV2,
    Hangul,
    HangulJamo,
    HanifiRohingya,
    Hanunoo,
    Hatran,
    Hebrew,
    Hiragana,
    ImperialAramaic,
    InscriptionalPahlavi,
    InscriptionalParthian,
    Javanese,
    Kaithi,
    Kannada,
    KannadaV2,
    Katakana,
    KayahLi,
    Kharosthi,
    KhitanSmallScript,
    Khmer,
    Khojki,
    Khudawadi,
    Lao,
    Latin,
    Lepcha,
    Limbu,
    LinearA,
    LinearB,
    LisuFraser,
    Lycian,
    Lydian,
    Mahajani,
    Makasar,
    Malayalam,
    MalayalamV2,
    Mandaic,
    Manichaean,
    Marchen,
    MasaramGondi,
    MathematicalAlphanumericSymbols,
    Medefaidrin,
    MeiteiMayek,
    MendeKikakui,
    MeroiticCursive,
    MeroiticHieroglyphs,
    Miao,
    Modi,
    Mongolian,
    Mro,
    Multani,
    MusicalSymbols,
    Myanmar,
    MyanmarV2,
    Nabataean,
    Nandinagari,
    Newa,
    NewTaiLue,
    NKo,
    Nushu,
    NyiakengPuachueHmong,
    Odia,
    OdiaV2,
    Ogham,
    OlChiki,
    OldItalic,
    OldHungarian,
    OldNorthArabian,
    OldPermic,
    OldPersianCuneiform,
    OldSogdian,
    OldSouthArabian,
    OldTurkic,
    Osage,
    Osmanya,
    PahawhHmong,
    Palmyrene,
    PauCinHau,
    Phagspa,
    Phoenician,
    PsalterPahlavi,
    Rejang,
    Runic,
    Samaritan,
    Saurashtra,
    Sharada,
    Shavian,
    Siddham,
    SignWriting,
    Sinhala,
    Sogdian,
    SoraSompeng,
    Soyombo,
    SumeroAkkadianCuneiform,
    Sundanese,
    SylotiNagri,
    Syriac,
    Tagalog,
    Tagbanwa,
    TaiLe,
    TaiTham,
    TaiViet,
    Takri,
    Tamil,
    TamilV2,
    Tangut,
    Telugu,
    TeluguV2,
    Thaana,
    Thai,
    Tibetan,
    Tifinagh,
    Tirhuta,
    UgariticCuneiform,
    Vai,
    Wancho,
    WarangCiti,
    Yezidi,
    Yi,
    ZanabazarSquare,
}

impl Script {
    pub(crate) fn tag(&self) -> Tag {
        match self {
            Script::Adlam => Tag::from_str("adlm").unwrap(),
            Script::Ahom => Tag::from_str("ahom").unwrap(),
            Script::AnatolianHieroglyphs => Tag::from_str("hluw").unwrap(),
            Script::Arabic => Tag::from_str("arab").unwrap(),
            Script::Armenian => Tag::from_str("armn").unwrap(),
            Script::Avestan => Tag::from_str("avst").unwrap(),
            Script::Balinese => Tag::from_str("bali").unwrap(),
            Script::Bamum => Tag::from_str("bamu").unwrap(),
            Script::BassaVah => Tag::from_str("bass").unwrap(),
            Script::Batak => Tag::from_str("batk").unwrap(),
            Script::Bengali => Tag::from_str("beng").unwrap(),
            Script::BengaliV2 => Tag::from_str("bng2").unwrap(),
            Script::Bhaiksuki => Tag::from_str("bhks").unwrap(),
            Script::Bopomofo => Tag::from_str("bopo").unwrap(),
            Script::Brahmi => Tag::from_str("brah").unwrap(),
            Script::Braille => Tag::from_str("brai").unwrap(),
            Script::Buginese => Tag::from_str("bugi").unwrap(),
            Script::Buhid => Tag::from_str("buhd").unwrap(),
            Script::ByzantineMusic => Tag::from_str("byzm").unwrap(),
            Script::CanadianSyllabics => Tag::from_str("cans").unwrap(),
            Script::Carian => Tag::from_str("cari").unwrap(),
            Script::CaucasianAlbanian => Tag::from_str("aghb").unwrap(),
            Script::Chakma => Tag::from_str("cakm").unwrap(),
            Script::Cham => Tag::from_str("cham").unwrap(),
            Script::Cherokee => Tag::from_str("cher").unwrap(),
            Script::Chorasmian => Tag::from_str("chrs").unwrap(),
            Script::CJKIdeographic => Tag::from_str("hani").unwrap(),
            Script::Coptic => Tag::from_str("copt").unwrap(),
            Script::CypriotSyllabary => Tag::from_str("cprt").unwrap(),
            Script::Cyrillic => Tag::from_str("cyrl").unwrap(),
            Script::Default => Tag::from_str("DFLT").unwrap(),
            Script::Deseret => Tag::from_str("dsrt").unwrap(),
            Script::Devanagari => Tag::from_str("deva").unwrap(),
            Script::DevanagariV2 => Tag::from_str("dev2").unwrap(),
            Script::DivesAkuru => Tag::from_str("diak").unwrap(),
            Script::Dogra => Tag::from_str("dogr").unwrap(),
            Script::Duployan => Tag::from_str("dupl").unwrap(),
            Script::EgyptianHieroglyphs => Tag::from_str("egyp").unwrap(),
            Script::Elbasan => Tag::from_str("elba").unwrap(),
            Script::Elymaic => Tag::from_str("elym").unwrap(),
            Script::Ethiopic => Tag::from_str("ethi").unwrap(),
            Script::Georgian => Tag::from_str("geor").unwrap(),
            Script::Glagolitic => Tag::from_str("glag").unwrap(),
            Script::Gothic => Tag::from_str("goth").unwrap(),
            Script::Grantha => Tag::from_str("gran").unwrap(),
            Script::Greek => Tag::from_str("grek").unwrap(),
            Script::Gujarati => Tag::from_str("gujr").unwrap(),
            Script::GujaratiV2 => Tag::from_str("gjr2").unwrap(),
            Script::GunjalaGondi => Tag::from_str("gong").unwrap(),
            Script::Gurmukhi => Tag::from_str("guru").unwrap(),
            Script::GurmukhiV2 => Tag::from_str("gur2").unwrap(),
            Script::Hangul => Tag::from_str("hang").unwrap(),
            Script::HangulJamo => Tag::from_str("jamo").unwrap(),
            Script::HanifiRohingya => Tag::from_str("rohg").unwrap(),
            Script::Hanunoo => Tag::from_str("hano").unwrap(),
            Script::Hatran => Tag::from_str("hatr").unwrap(),
            Script::Hebrew => Tag::from_str("hebr").unwrap(),
            Script::Hiragana => Tag::from_str("kana").unwrap(),
            Script::ImperialAramaic => Tag::from_str("armi").unwrap(),
            Script::InscriptionalPahlavi => Tag::from_str("phli").unwrap(),
            Script::InscriptionalParthian => Tag::from_str("prti").unwrap(),
            Script::Javanese => Tag::from_str("java").unwrap(),
            Script::Kaithi => Tag::from_str("kthi").unwrap(),
            Script::Kannada => Tag::from_str("knda").unwrap(),
            Script::KannadaV2 => Tag::from_str("knd2").unwrap(),
            Script::Katakana => Tag::from_str("kana").unwrap(),
            Script::KayahLi => Tag::from_str("kali").unwrap(),
            Script::Kharosthi => Tag::from_str("khar").unwrap(),
            Script::KhitanSmallScript => Tag::from_str("kits").unwrap(),
            Script::Khmer => Tag::from_str("khmr").unwrap(),
            Script::Khojki => Tag::from_str("khoj").unwrap(),
            Script::Khudawadi => Tag::from_str("sind").unwrap(),
            Script::Lao => Tag::from_str("lao ").unwrap(),
            Script::Latin => Tag::from_str("latn").unwrap(),
            Script::Lepcha => Tag::from_str("lepc").unwrap(),
            Script::Limbu => Tag::from_str("limb").unwrap(),
            Script::LinearA => Tag::from_str("lina").unwrap(),
            Script::LinearB => Tag::from_str("linb").unwrap(),
            Script::LisuFraser => Tag::from_str("lisu").unwrap(),
            Script::Lycian => Tag::from_str("lyci").unwrap(),
            Script::Lydian => Tag::from_str("lydi").unwrap(),
            Script::Mahajani => Tag::from_str("mahj").unwrap(),
            Script::Makasar => Tag::from_str("maka").unwrap(),
            Script::Malayalam => Tag::from_str("mlym").unwrap(),
            Script::MalayalamV2 => Tag::from_str("mlm2").unwrap(),
            Script::Mandaic => Tag::from_str("mand").unwrap(),
            Script::Manichaean => Tag::from_str("mani").unwrap(),
            Script::Marchen => Tag::from_str("marc").unwrap(),
            Script::MasaramGondi => Tag::from_str("gonm").unwrap(),
            Script::MathematicalAlphanumericSymbols => Tag::from_str("math").unwrap(),
            Script::Medefaidrin => Tag::from_str("medf").unwrap(),
            Script::MeiteiMayek => Tag::from_str("mtei").unwrap(),
            Script::MendeKikakui => Tag::from_str("mend").unwrap(),
            Script::MeroiticCursive => Tag::from_str("merc").unwrap(),
            Script::MeroiticHieroglyphs => Tag::from_str("mero").unwrap(),
            Script::Miao => Tag::from_str("plrd").unwrap(),
            Script::Modi => Tag::from_str("modi").unwrap(),
            Script::Mongolian => Tag::from_str("mong").unwrap(),
            Script::Mro => Tag::from_str("mroo").unwrap(),
            Script::Multani => Tag::from_str("mult").unwrap(),
            Script::MusicalSymbols => Tag::from_str("musc").unwrap(),
            Script::Myanmar => Tag::from_str("mymr").unwrap(),
            Script::MyanmarV2 => Tag::from_str("mym2").unwrap(),
            Script::Nabataean => Tag::from_str("nbat").unwrap(),
            Script::Nandinagari => Tag::from_str("nand").unwrap(),
            Script::Newa => Tag::from_str("newa").unwrap(),
            Script::NewTaiLue => Tag::from_str("talu").unwrap(),
            Script::NKo => Tag::from_str("nko ").unwrap(),
            Script::Nushu => Tag::from_str("nshu").unwrap(),
            Script::NyiakengPuachueHmong => Tag::from_str("hmnp").unwrap(),
            Script::Odia => Tag::from_str("orya").unwrap(),
            Script::OdiaV2 => Tag::from_str("ory2").unwrap(),
            Script::Ogham => Tag::from_str("ogam").unwrap(),
            Script::OlChiki => Tag::from_str("olck").unwrap(),
            Script::OldItalic => Tag::from_str("ital").unwrap(),
            Script::OldHungarian => Tag::from_str("hung").unwrap(),
            Script::OldNorthArabian => Tag::from_str("narb").unwrap(),
            Script::OldPermic => Tag::from_str("perm").unwrap(),
            Script::OldPersianCuneiform => Tag::from_str("xpeo").unwrap(),
            Script::OldSogdian => Tag::from_str("sogo").unwrap(),
            Script::OldSouthArabian => Tag::from_str("sarb").unwrap(),
            Script::OldTurkic => Tag::from_str("orkh").unwrap(),
            Script::Osage => Tag::from_str("osge").unwrap(),
            Script::Osmanya => Tag::from_str("osma").unwrap(),
            Script::PahawhHmong => Tag::from_str("hmng").unwrap(),
            Script::Palmyrene => Tag::from_str("palm").unwrap(),
            Script::PauCinHau => Tag::from_str("pauc").unwrap(),
            Script::Phagspa => Tag::from_str("phag").unwrap(),
            Script::Phoenician => Tag::from_str("phnx").unwrap(),
            Script::PsalterPahlavi => Tag::from_str("phlp").unwrap(),
            Script::Rejang => Tag::from_str("rjng").unwrap(),
            Script::Runic => Tag::from_str("runr").unwrap(),
            Script::Samaritan => Tag::from_str("samr").unwrap(),
            Script::Saurashtra => Tag::from_str("saur").unwrap(),
            Script::Sharada => Tag::from_str("shrd").unwrap(),
            Script::Shavian => Tag::from_str("shaw").unwrap(),
            Script::Siddham => Tag::from_str("sidd").unwrap(),
            Script::SignWriting => Tag::from_str("sgnw").unwrap(),
            Script::Sinhala => Tag::from_str("sinh").unwrap(),
            Script::Sogdian => Tag::from_str("sogd").unwrap(),
            Script::SoraSompeng => Tag::from_str("sora").unwrap(),
            Script::Soyombo => Tag::from_str("soyo").unwrap(),
            Script::SumeroAkkadianCuneiform => Tag::from_str("xsux").unwrap(),
            Script::Sundanese => Tag::from_str("sund").unwrap(),
            Script::SylotiNagri => Tag::from_str("sylo").unwrap(),
            Script::Syriac => Tag::from_str("syrc").unwrap(),
            Script::Tagalog => Tag::from_str("tglg").unwrap(),
            Script::Tagbanwa => Tag::from_str("tagb").unwrap(),
            Script::TaiLe => Tag::from_str("tale").unwrap(),
            Script::TaiTham => Tag::from_str("lana").unwrap(),
            Script::TaiViet => Tag::from_str("tavt").unwrap(),
            Script::Takri => Tag::from_str("takr").unwrap(),
            Script::Tamil => Tag::from_str("taml").unwrap(),
            Script::TamilV2 => Tag::from_str("tml2").unwrap(),
            Script::Tangut => Tag::from_str("tang").unwrap(),
            Script::Telugu => Tag::from_str("telu").unwrap(),
            Script::TeluguV2 => Tag::from_str("tel2").unwrap(),
            Script::Thaana => Tag::from_str("thaa").unwrap(),
            Script::Thai => Tag::from_str("thai").unwrap(),
            Script::Tibetan => Tag::from_str("tibt").unwrap(),
            Script::Tifinagh => Tag::from_str("tfng").unwrap(),
            Script::Tirhuta => Tag::from_str("tirh").unwrap(),
            Script::UgariticCuneiform => Tag::from_str("ugar").unwrap(),
            Script::Vai => Tag::from_str("vai ").unwrap(),
            Script::Wancho => Tag::from_str("wcho").unwrap(),
            Script::WarangCiti => Tag::from_str("wara").unwrap(),
            Script::Yezidi => Tag::from_str("yezi").unwrap(),
            Script::Yi => Tag::from_str("yi  ").unwrap(),
            Script::ZanabazarSquare => Tag::from_str("zanb").unwrap(),
        }
    }
}

impl Default for Script {
    fn default() -> Script {
        Script::Default
    }
}
